# Generated by Django 5.2.1 on 2025-06-04 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=255, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('order_type', models.CharField(choices=[('common', 'Общий клининг'), ('general', 'Генеральная уборка'), ('pastbuild', 'Послестроительная уборка'), ('chemical', 'Химчистка ковров'), ('furniture', 'Мебель')], max_length=255)),
                ('other', models.BooleanField(default=False)),
                ('comment_others', models.TextField(blank=True)),
                ('payment_type', models.CharField(choices=[('cash', 'Наличные'), ('card', 'Банковская карта')], max_length=255)),
                ('status', models.CharField(choices=[('process', 'В работе'), ('confirm', 'Выполнено'), ('reject', 'Отменено')], max_length=255)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
