# Generated by Django 5.2.1 on 2025-06-04 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0002_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('cash', 'Наличные'), ('card', 'Банковская карта')], max_length=255, null=True),
        ),
    ]
