# Generated by Django 5.2.1 on 2025-06-04 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0003_alter_order_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='other',
            field=models.CharField(default=False),
        ),
    ]
