# Generated by Django 5.2.1 on 2025-06-04 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0004_alter_order_other'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comment_others',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='other',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Наличные'), ('card', 'Банковская карта')], max_length=255),
        ),
    ]
