# Generated by Django 5.2.1 on 2025-06-04 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0005_alter_order_comment_others_alter_order_other_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment_by_admin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('process', 'В работе'), ('confirm', 'Выполнено'), ('reject', 'Отменено')], default='process', max_length=255),
        ),
    ]
