# Generated by Django 5.2.1 on 2025-06-04 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0006_order_comment_by_admin_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='other',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
