# Generated by Django 5.2.1 on 2025-06-04 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0007_alter_order_other'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(max_length=255),
        ),
    ]
